spring.application.name=auth-server
spring.config.import=optional:configserver:http://localhost:8888


# CloudAMQP Connection Details
spring.rabbitmq.host=puffin.rmq2.cloudamqp.com
spring.rabbitmq.port=5671
spring.rabbitmq.username=vylizifg
spring.rabbitmq.password=plWlHvujAXYv6g1T29j6GWDSA121XMbt
spring.rabbitmq.virtual-host=vylizifg

# Enable SSL/TLS for secure communication over the internet
spring.rabbitmq.ssl.enabled=true