spring.application.name=eureka-server
server.port=8761
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
# Expose health and metrics endpoints specifically
management.endpoints.web.exposure.include=health,metrics

eureka.server.eviction-interval-timer-in-ms=2000
eureka.server.enable-self-preservation=false