# Shared Logging levels
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG

# from the below swagger URL each request will be forwarded to the respective service's API docs endpoint
app.gateway.url=http://api-gateway:8080

eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka


# Expose the health endpoint to the network
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always