# ===================================================================
# GLOBAL LOGGING LEVELS
# ===================================================================
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG

# ===================================================================
# GLOBAL key to validate request comes from apigateway or not
# 
app.internal.secret=MySuperSecretInternalKey@123


# ===================================================================
# GATEWAY URL (for Swagger doc generation)
# ===================================================================
app.gateway.url=http://localhost:8080

# ===================================================================
# REDIS
# ===================================================================
# spring.data.redis.host=innocent-hyena-147929.upstash.io
# spring.data.redis.password=gQAAAAAAAmXlAAIgcDE4MjhjYWZjMGM4NmM0ODIxOGVlNGMyYTMzM2FkNTMzNA
# spring.data.redis.port=6379
# spring.data.redis.ssl.enabled=true

spring.data.redis.url=rediss://default:gQAAAAAAAmXlAAIgcDE4MjhjYWZjMGM4NmM0ODIxOGVlNGMyYTMzM2FkNTMzNA@settling-duckling-157157.upstash.io:6379
# ===================================================================
# EUREKA REGISTRATION
# ===================================================================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}

# ===================================================================
# ACTUATOR & HEALTH PROBES (Global baseline)
# ===================================================================
management.endpoints.web.exposure.include=health,metrics
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
management.health.livenessState.enabled=true
management.health.readinessState.enabled=true


# Razorpay Test Keys
razorpay.key.id=rzp_test_SyKFOG7Dsvus9g
razorpay.key.secret=iFaOJ7AT3TXP4sgWloPXiCjM



# CloudAMQP Connection Details
spring.rabbitmq.host=puffin.rmq2.cloudamqp.com
spring.rabbitmq.port=5671
spring.rabbitmq.username=vylizifg
spring.rabbitmq.password=plWlHvujAXYv6g1T29j6GWDSA121XMbt
spring.rabbitmq.virtual-host=vylizifg

# Enable SSL/TLS for secure communication over the internet
spring.rabbitmq.ssl.enabled=true
