spring.threads.virtual.enabled=true

server.port=8082

# ── H2 ───────────────────────────────────────────────────────────────────────
spring.datasource.url=jdbc:h2:mem:datadb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2 console → http://localhost:8082/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

springdoc.api-docs.path=/data/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.enabled=true

# Razorpay Test Keys
razorpay.key.id=rzp_test_SyKFOG7Dsvus9g
razorpay.key.secret=iFaOJ7AT3TXP4sgWloPXiCjM
